### ISSUE TITLE
zsh-autosuggestions can't display in vterm

### ISSUE THREAD

**Issue by Eason0210** [purcell/color-theme-sanityinc-tomorrow#165]
Hi @purcell 

Thanks for making these excellent  themes, I use it every day.

But when I use [vterm](https://github.com/akermu/emacs-libvterm) with theme `sanityinc-tomorrow-bright` and `sanityinc-tomorrow-day`, the autosuggestion can't display, which is supported by [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) plugin.

It works as expected in `term` and `ansi-term` with these themes.

It also works well in `vterm` with Emacs's default theme.

Examples:

Works with` sanityinc-tomorrow-bright`, when I input `brew in`, only show one char of the suggestion, expected is `brew install libvterm`:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/47546452/162600886-ebd2095b-f875-42fc-8b9c-48540f4a315d.png">

Works with `sanityinc-tomorrow-day`:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/47546452/162601060-37679b86-8c5e-4e51-ad84-b0b6870dab29.png">

when toggle from ` sanityinc-tomorrow-bright` to `sanityinc-tomorrow-day`, you can see the suggestion word.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/47546452/162601084-ab1d7d56-49b1-41b5-9cab-33c5e7bbeebc.png">

Works well as expected in Emacs's default theme, I input ` brew insta` and get the result as below picture:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/47546452/162601402-686e2b46-d701-4037-8a16-417e26843f14.png">

Works well with the builtin `modus-themes` theme:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/47546452/162602456-ee590bfd-a81d-4ed5-8e0c-3d6252daa4a2.png">

Emacs version : 29.0.50 latest commit
OS: macOS Monterey 12.3.1

**Comment by purcell** [comment]
Hmm, this is probably related to [these recent changes](https://github.com/purcell/color-theme-sanityinc-tomorrow/commit/73831f251d068d434ad31ed4d22e5af9f2326f0d) which I have not tested thoroughly. The underlying Emacs changes were made in a way that makes it hard to keep forward/backward compatibility in themes.

**Comment by purcell** [comment]
Fixed now, I think. The default styling of those faces in `vterm.el` is completely broken, so overrides are necessary.

**Comment by Eason0210** [comment]
I try the [latest commit/393eb25](https://github.com/purcell/color-theme-sanityinc-tomorrow/commit/393eb25), issue still exist. see the picture below:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/47546452/162777222-bed62030-c739-46d6-a893-0847040519f0.png">

**Comment by purcell** [comment]
I can't easily reproduce this locally without figuring out how to get `zsh-autosuggestions` installed 😢

**Comment by Eason0210** [comment]
The issue is from `vterm-color-black`.  
```emacs-lisp
(vterm-color-black (:background ,comment :foreground ,comment))
(vterm-color-underline (:foreground ,aqua :underline t))
(vterm-color-inverse-video (:background ,background :inverse-video t)
```
with my local change as above, and it works as expected. `zsh-autosuggestions` is using the `vterm-color-black`. 
Here I choose the color `aqua` for underline and `comment` for black, just for test. 
May be you have a better choice 😄 

<img width="294" alt="image" src="https://user-images.githubusercontent.com/47546452/162852078-36f5fbd7-2191-4704-8c5f-1f6e2f2311af.png">

I run `describe-char` for the char `b` in  the word` libvterm`, and got the information as below:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/47546452/162853615-0e2b7084-7eea-403d-807d-5efe83fbe9a6.png">

I run `describe-char` for the char `n` in  the word` install`, and got the information as below:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/47546452/162853556-33d40c60-de2a-4588-b371-f5a5e4065176.png">

> I can't easily reproduce this locally without figuring out how to get `zsh-autosuggestions` installed 😢

To install `zsh-autosuggestions` , you can reference the [Install.md](https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md), I use the `Oh-my-zsh` way.

If you are using Nix, may be you can reference my personal Nix config, it works well. But I don't use nix on macOS recently and switch back to use Brew.
https://github.com/Eason0210/system/blob/34c4e7a7433536671745ccfa778576963d912c72/modules/home-manager/cli/default.nix#L112-L167

**Comment by Eason0210** [comment]
Great, now it works well in vterm and term/ansi-term.

vterm:

<img width="380" alt="image" src="https://user-images.githubusercontent.com/47546452/163073947-284a80df-031e-4925-ab1c-ca9e48b2f617.png">

<img width="380" alt="image" src="https://user-images.githubusercontent.com/47546452/163073767-24c43dc9-7af1-4835-a935-e88e4de176a4.png">

ansi-term :

<img width="380" alt="image" src="https://user-images.githubusercontent.com/47546452/163074023-a7856ad4-e4ca-4103-aff5-f31ca43ec063.png">

<img width="381" alt="image" src="https://user-images.githubusercontent.com/47546452/163073701-86b6b708-6ab8-4f24-aad4-1a0a30f7cea1.png">

Meanwhile, thanks for your detailed  explanation and the perl man page, It help me a lot to learn about ansi-color.

**Comment by purcell** [comment]
Yay, thanks for your help with this. I'm using Nix for my config, but I'm not really using home-manager, and nix-darwin doesn't support that plugin, so I was in danger of getting derailed.

In the end I found a handy one-liner for printing out a colour table, which helped me iterate through options:

```sh
for x in {0..8}; do for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "; done; echo; done; done; echo ""
```
